name: Deploy Vulnerable Application                                  # workflow name

on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gcerrillo-vwapp"
          heroku_email: "gastoncerrillo@gmail.com"
          remote_branch: "master"
          usedocker: true