on:
  push:
    branches:
      - staging

jobs:
  run-snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build an image
      run: docker build . -t synk-image       
    - name: Run Snyk to check image for vulnerabilities
      # continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
      with:
        image: synk-image
        args: --file=Dockerfile
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif