on:
  push:
    branches:
      - staging

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan with OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://gcerrillo-vwapp-staging.herokuapp.com/'